### ISSUE TITLE
All sources stop sending and receiving audio on Scene Collection change.

### ISSUE THREAD

**Issue by ALEXonyourscreen** [norihiro/obs-vban#2]
When changing from one Scene Collection to another, all VBAN Audio Sources (incoming and outgoing) stop working completely. Updating stream name, port, or IP addresses does not fix this, and restarting OBS does not fix this. A full Windows reboot is the only solution I have found.

No crash on exit, nothing in the logs (other than when the streams were initialized properly on first load)

Windows 11 22H2 - OS Build 22622.586
OBS 28.1.2

The only other plugin that I am using that interacts with audio (that I am aware of) is Advanced Scene Switcher.

Thanks for the plugin Norihiro, even with this issue it has been a complete game changer for my setup!

**Comment by ALEXonyourscreen** [comment]
Quick update: running OBS with VBAN plugin working as expected, then restarting OBS, also causes the sources to stop transmitting.

So it only seems to work on first launch of OBS after booting the OS.

**Comment by norihiro** [comment]
Thank you so much for reporting this bug. I'm sorry for the inconvenience.
You can download a fixed version from this page. https://github.com/norihiro/obs-vban/releases/tag/0.2.3
