### ISSUE TITLE
Feature request DNS hostnames

### ISSUE THREAD

**Issue by MarekPro1** [norihiro/obs-vban#8]
Hello can you please add a feature that insead of using classic IP address you can write an DNS address? Thank you very much.

**Comment by norihiro** [comment]
Could you let me know how important the DNS resolution is?
From the implementation point of view, it takes time to resolve the name from DNS, so it would be complicated to avoid audio packets being dropped or UI freezing during the DNS resolution.

**Comment by MarekPro1** [comment]
Hello, in VBMatrix i also use dns for vban with the lowest latency streams.
And iam not exactly sure how they do that but I think it should be fine.
Youre the profesional, and if its not posible okay I will be little sad.
But I want to use your plugin.

**Comment by MarekPro1** [comment]
Hello, if you merged it to main and didn't made a whole realese, how can I added to my obs. Or how does it work. Thank you.

**Comment by norihiro** [comment]
I'm preparing the release together with some other changes but you can download from the latest binary from Actions tab or https://github.com/norihiro/obs-vban/actions/runs/11702366235 (The package for macOS is not signed, which may be problem. There is no issue for Windows.)

**Comment by MarekPro1** [comment]
Thank you again I learned something new.
